window.addthis_translations = [
    [
        ["es", "esl", "spa"],
        "Favorito / Compartir",
        "M\u00e1s...",
        "Enviar a un amigo",
        "Correo",
        "Favoritos",
        "\u00bfTiene varias direcciones? Use comas.",
        "Para",
        "De",
        "Nota",
        "Pol\u00edtica de privacidad: Nosotros nunca compartimos su informaci\u00f3n personal.",
        "Enviar",
        "Por favor, introduzca una direcci\u00f3n de correo electr\u00f3nico v\u00e1lida.",
        "Mensaje enviado!",
        "Suscribirse a la pagina",
        "escoger de estos lectores de la pagina",
        "Por Favor no me preguntes de nuevo, enviaselo directamente a mis seguidores",
        "Terminado",
        "Cons\u00edguete tu propio bot\u00f3n!",
        "direcci\u00f3n de correo electr\u00f3nico",
        "opcional",
        "m\u00e1ximo 255 letras",
        "Imprimir",
        "Que es esto?",
        "Privacidad",
        "Usar libreta de direcciones",
        "Cancelar",
        "Entrar para usar tus contactos",
        "Nombre de Usuario",
        "Contrase\u00f1a",
        "Recuerdame",
        "Ingresar",
        "Importar libreta de direcciones",
        "Error al iniciar sesion",
        "Solo 5 recipinetes porfavor!",
        "Encuentra un servicio",
        "No se encuentra el servicio",
        "Compartir otra vez",
        "Cerrar Sesi\u00f3n",
        "Reciviendo contactos",
        "Sugiera un servicio",
        "Compartida con \u00e9xito!",
        "Hacer m\u00e1s f\u00e1cil compartir con AddThis para Firefox.",
        "Descargar",
        "No muestre esto ",
        "Enviando mensaje ...",
        "Por favor, <a id=\"at16ecmc\" href=\"#\" onclick=\"_atw.rse();_atw.cef();return true\" target=\"_blank\">haga clic aqu\u00ed</a> para confirmar que es una persona de carne y hueso.",
        "Configuraci\u00f3n",
        "Lo sentimos, no podemos enviar este mensaje. Por favor, int\u00e9ntelo de nuevo en unos minutos.",
        "Por favor ayudanos a prevenir el correo no deseado!",
        "Escribe las dos palabras:",
        "Por favor, introduzca una respuesta v\u00e1lida.",
        "Lo sentimos, su respuesta era incorrecta.",
        "Acceder a personalizar",
        "Tema",
        "Enviar este correo electr\u00f3nico con diferentes servicios",
        "Escribir las letras en movimiento",
        "Firmar y hacer m\u00e1s f\u00e1cil compartir",
        "Ver un video",
        "Exito ha conectado!",
        "Cerrando la ventana en XXX segundos ...",
        "Personalizar",
        "Cuenta",
        "Enviar correo Electr\u00f3nico",
        "Reacci\u00f3n",
        "Compartir una idea, reportar un bug, o simplemente hacernos saber lo que piensas.",
        "Necesita ayuda?",
        "Enviar Comentarios",
        "Todos los Servicios Disponibles",
        "Mis Servicios Favoritos",
        "Restablecer los servicios a los valores predeterminados",
        "A\u00f1adir",
        "Quitar",
        "Guardar Los Cambios",
        "Personalice AddThis seleccionando hasta 10 de sus lugares favoritos para compartir.",
        ,
        ,
        "Hacer m\u00e1s f\u00e1cil compartir con la barra de herramientas AddThis",
        "Para dejar de recibir los correos electr\u00f3nicos de AddThis visite",
        "Enviado",
        "Su opini\u00f3n es muy importante para nosotros.",
        "Gracias por usar AddThis.",
        "Hola",
        "Conecte las cuentas sociales para activar Instant Share para Twitter y Facebook.",
        "Ver v\u00eddeo",
        "Todas las cuentas pueden utilizarse para registrarse y acceder al resto.",
        "Conecte otra cuenta.",
        "Estar\u00edamos lo siento que te vayas, pero puede eliminar su cuenta en cualquier momento.",
        "Eliminar cuenta.",
        "Desconectar",
        "Reordenar esta lista usando las flechas. ",
        "Compartir",
        "Por favor ingrese una nota m\u00e1s corta.",
        "No pudimos enviar su correo electr\u00f3nico.",
        "Aceptar",
        "Ups",
        "Seguir",
        "Gracias por compartir",
        "Gracias por seguirnos",
        "Recomendado para ti",
        "Comparte con [x]",
        "Siga en [x]",
        "Ingrese su direcci\u00f3n de correo electr\u00f3nico",
        "Su correo electr\u00f3nico",
        "Al hacer clic en el botón de arriba, está de acuerdo con que la información anterior sea enviada a los servidores de AddThis en EE. UU."
    ]
];

window.addthis_services_loc = 'facebook,twitter,print,google_plusone_share,email,gmail,mailto,pinterest_share,linkedin,favorites,tumblr';
window.addthis_services_loc_mob = 'facebook,whatsapp,twitter,mailto,google_plusone_share,pinterest_share,print,linkedin,gmail,tumblr';

if (window._ate) _ate.ed.fire("addthis.i18n.ready", window.addthis, {lng:"es"});
